/// @todo - need to match ./client/src/extension.ts 

export const TOKEN_TYPES = [
  'pdf_token',
  'header',
  'indirect_object_start',
  'endobj',
  'stream',
  'dict_start',
  'dict_end',
  'array_start',
  'array_end',
  'name',
  'valid_name_char',
  'name_hex_escape',
  'string_literal',
  'string_literal_char',
  'string_literal_escape',
  'octal',
  'octal_digit',
  'escaped_eol',
  'hex_string',
  'indirect_ref',
  'integer',
  'real',
  'bool',
  'null',
  'xref',
  'xref_10entry',
  'xref_5entry',
  'xref_entry',
  'trailer',
  'startxref',
  'eof',
  'comment',
  'eol',
  'delimiter',
  'start_delimiter',
  'end_delimiter',
  'ws_incl_eol',
  'ws_no_eol',
];

export const TOKEN_MODIFIERS = [
  'error',   
  'important'  
];
